export interface Producto {
    id:                   number;
    all:                  string;
    tipo:                 string;
    padre:                string;
    version:              string;
    titulo:               string;
    enlace:               string;
    subdominios:          string[];
    responsive:           string;
    subdominioResponsive: string;
    subdominioNewEra:     string;
    online:               string;
    imagenSrc:            string;
}

export class ProductoTotal {
    producto = PRODUCTO;
}
 var PRODUCTO: Producto[] = [
    {
        "id":1,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de redumas",
        "version":"new-era",
        "titulo":"11essences",
        "enlace":"http://11essences.net/",
        "subdominios":["http://11essences.net/f"],
        "responsive": "responsiveSi",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/11essences.jpg"
    },
    {
        "id":2,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de redumas",
        "version":"old-era",
        "titulo":"11plantas",
        "enlace":"http://www.11plantas.com/",
        "subdominios":["http://www.11plantas.com/11plahfb/","http://www.11plantas.com/landing_1/","http://www.11plantas.com/landing_2/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/11plantas.jpg"
    },
    {
        "id":3,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de redumas",
        "version":"new-era",
        "titulo":"11plantas",
        "enlace":"http://www.11plantas.net/",
        "subdominios":["http://www.11plantas.net/f/"],
        "responsive": "responsiveSi",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/11plantas.jpg"
    },
    {
        "id":4,
        "all":"all",
        "tipo":"s/definir",
        "padre":"",
        "version":"old-era",
        "titulo":"addsvr",
        "enlace":"http://www.addsvr.com/",
        "subdominios":[],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online":"offline",
        "imagenSrc":"http://worldshopmart.com/todosProductos/img/default.png"
    },
    {
        "id":5,
        "all":"all",
        "tipo":"s/definir",
        "padre":"",
        "version":"old-era",
        "titulo":"adelga-fit",
        "enlace":"http://www.adelga-fit.com/",
        "subdominios":[],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online":"offline",
        "imagenSrc":"http://worldshopmart.com/todosProductos/img/default.png"
    },
    {
        "id":6,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de lipodrene",
        "version":"old-era",
        "titulo":"adipogel",
        "enlace":"http://adipogel.com/",
        "subdominios":["http://www.adipogel.com/f/","http://www.adipogel.com/index1/","http://www.adipogel.com/index2/","http://www.adipogel.com/mail1/","http://www.adipogel.com/mail2/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/adipogel.jpg"
    },
    {
        "id":7,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de alivialiv",
        "version":"new-era",
        "titulo":"aliviaflex",
        "enlace":"http://aliviaflex.com/",
        "subdominios":["http://aliviaflex.com/f/","http://aliviaflex.com/mail1/","http://aliviaflex.com/index1/"],
        "responsive": "subResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/aliviaflex.jpg"
    },
    {
        "id":8,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"new-era",
        "titulo":"alivialiv",
        "enlace":"http://alivialiv.com/",
        "subdominios":["http://www.alivialiv.com/f/","http://www.alivialiv.com/zeti-t/","http://www.alivialiv.com/landing_1/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra": "new-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/alivialiv.jpg"
    },
    {
        "id":9,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de redumas",
        "version":"old-era",
        "titulo":"11essences",
        "enlace":"http://www.bajar-peso-ya.com/",
        "subdominios":["http://www.bajar-peso-ya.com/f/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/11essences.jpg"
    },
    {
        "id":10,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de pulmo2",
        "version":"new-era",
        "titulo":"I-Quit",
        "enlace":"http://www.bastadefumar.com/",
        "subdominios":["http://www.bastadefumar.com/f/"],
        "responsive": "responsiveSi",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra": "new-era",
        "online": "online",
        "imagenSrc":"http://www.bastadefumar.com/img/pack.png"
    },
    {
        "id":11,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de dermacel",
        "version":"new-era",
        "titulo":"biolift",
        "enlace":"http://bio-lift.net/",
        "subdominios":["http://bio-lift.net/f/","http://bio-lift.net/landing_fb/"],
        "responsive": "responsiveSi",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/biolift.jpg"
    },
    {
        "id":12,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de varilyne",
        "version":"new-era",
        "titulo":"biolux",
        "enlace":"http://bio-lux.net/",
        "subdominios":["http://bio-lux.net/f/","http://bio-lux.net/index1/"],
        "responsive": "responsiveSi",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra": "new-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/biolux.jpg"
    },
    {
        "id":13,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de busto perfecto",
        "version":"old-era",
        "titulo":"Bubby",
        "enlace":"http://www.bubby-cream.com/",
        "subdominios":[],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/bubby.jpg"
    },
    {
        "id":14,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de busto perfecto",
        "version":"old-era",
        "titulo":"Bubby",
        "enlace":"http://www.bubbygel.com/",
        "subdominios":["http://www.bubbygel.com/index1/","http://www.bubbygel.com/mail1/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/bubby.jpg"
    },
    {
        "id":15,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"bubby plus",
        "enlace":"http://www.bubbyplus.com/",
        "subdominios":[],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online":"offline",
        "imagenSrc":"http://worldshopmart.com/img/bubbyplus.jpg"
    },
    {
        "id":16,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"busto perfecto",
        "enlace":"http://www.bustoperfecto.com/",
        "subdominios":["http://www.bustoperfecto.com/fb2/","http://www.bustoperfecto.com/fb/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra": "new-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/bustoperfecto.jpg"
    },
    {
        "id":17,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de busto perfecto",
        "version":"old-era",
        "titulo":"Realz",
        "enlace":"http://www.bustup-vol.com/",
        "subdominios":["http://www.bustup-vol.com/bubby/","http://www.bustup-vol.com/f/","http://www.bustup-vol.com/g/","http://www.bustup-vol.com/fb/","http://www.bustup-vol.com/mail1/","http://www.bustup-vol.com/index1/","http://www.bustup-vol.com/dp/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra": "new-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/realz.jpg"
    },
    {
        "id":18,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"new-era",
        "titulo":"cafenat",
        "enlace":"http://www.cafenat.com/",
        "subdominios":["http://www.cafenat.com/bajardepeso/","http://www.cafenat.com/f/","http://www.cafenat.com/perderpeso/","http://www.cafenat.com/fan/","http://www.cafenat.com/oferta/","http://www.cafenat.com/test/","http://www.cafenat.com/social/3458/","http://www.cafenat.com/primicias/3469/"],
        "responsive": "responsiveSi",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra": "new-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/cafenat.jpg"
    },
    {
        "id":19,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"calvifin",
        "enlace":"http://www.calvifin.com/",
        "subdominios":["http://www.calvifin.com/f/","http://www.calvifin.com/mobile1/","http://www.calvifin.com/mobile/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra": "new-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/calvifin.jpg"
    },
    {
        "id":20,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de crembios",
        "version":"old-era",
        "titulo":"celulift",
        "enlace":"http://www.celulift.com/",
        "subdominios":["http://www.celulift.com/f/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/celulift.jpg"
    },
    {
        "id":21,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"clorophila",
        "enlace":"http://www.clorophila-salud.com/",
        "subdominios":["http://www.clorophila-salud.com/f/","http://www.clorophila-salud.com/index2/","http://www.clorophila-salud.com/mail2/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/todosProductos/img/clorophila-liquida.jpg"
    },
    {
        "id":22,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de cafenat",
        "version":"old-era",
        "titulo":"cofigrin",
        "enlace":"http://www.cofigrin-adelgaza.com/",
        "subdominios":[],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/cofigrin.jpg"
    },
    {
        "id":23,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de cafenat",
        "version":"old-era",
        "titulo":"cofigrin",
        "enlace":"http://www.cofigrin.com/",
        "subdominios":["http://www.cofigrin.com/index1/","http://www.cofigrin.com/index3/","http://www.cofigrin.com/todosalud/","http://www.cofigrin.com/ts_mail/","http://www.cofigrin.com/mail/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/cofigrin.jpg"
    },
    {
        "id":24,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de intesplus",
        "version":"new-era",
        "titulo":"colactivepro",
        "enlace":"http://www.colactivepro.com/",
        "subdominios":["http://www.colactivepro.com/f/"],
        "responsive": "responsiveSi",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra": "new-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/colactivepro.jpg"
    },
    {
        "id":25,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de intesplus",
        "version":"old-era",
        "titulo":"colondetox",
        "enlace":"http://www.colon-detoxen.com/",
        "subdominios":["http://www.colon-detoxen.com/f/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/colondetox.jpg"
    },
    {
        "id":26,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"new-era",
        "titulo":"dermacel",
        "enlace":"http://www.dermacel.net",
        "subdominios":["http://dermacel.net/fanpage/","http://dermacel.net/fbh/","http://dermacel.net/index1/"],
        "responsive": "responsiveSi",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/dermacel.jpg"
    },
    {
        "id":27,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de redumas",
        "version":"old-era",
        "titulo":"dietmeal",
        "enlace":"http://www.diet-meal.com/",
        "subdominios":["http://www.diet-meal.com/landing_1/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/dietmeal.jpg"
    },
    {
        "id":28,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de redumas",
        "version":"old-era",
        "titulo":"XeniPlus",
        "enlace":"http://www.dieta-ya.com/",
        "subdominios":[],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/xeniplus.jpg"
    },
    {
        "id":29,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"Sueño Reparador",
        "enlace":"http://dormirmejor.net/",
        "subdominios":["http://dormirmejor.net/f/"],
        "responsive": "responsiveSi",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://dormirmejor.net/images/camb1.png"
    },
    {
        "id":30,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"durasex",
        "enlace":"http://www.dura-s.com/",
        "subdominios":["http://www.dura-s.com/f/"],
        "responsive": "responsiveSi",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/durasex.jpg"
    },
    {
        "id":31,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de durasex",
        "version":"old-era",
        "titulo":"duraplen",
        "enlace":"http://www.duraplen.com/",
        "subdominios":["http://www.duraplen.com/landing_1/","http://www.duraplen.com/poringa/1609/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/duraplen.jpg"
    },
    {
        "id":32,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"empresarias en casa",
        "enlace":"http://www.empresariaencasa.com/",
        "subdominios":["http://www.empresariaencasa.com/f/"],
        "responsive": "responsiveSi",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://www.empresariaencasa.com/images/bokeh_car_lights_bg.jpg"
    },
    {
        "id":33,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de enciclosex",
        "version":"old-era",
        "titulo":"enciclosex",
        "enlace":"http://enciclosex.com/",
        "subdominios":["http://enciclosex.com/landing_1/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/enciclosex.jpg"
    },
    {
        "id":34,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"enciclosex",
        "enlace":"http://www.enciclovig.com/",
        "subdominios":["http://www.enciclovig.com/f/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/enciclosex.jpg"
    },
    {
        "id":35,
        "all":"all",
        "tipo":"s/definir",
        "padre":"",
        "version":"old-era",
        "titulo":"flower",
        "enlace":"http://www.excellenceflower.com/",
        "subdominios":[],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online":"offline",
        "imagenSrc":"http://worldshopmart.com/todosProductos/img/default.png"
    },
    {
        "id":36,
        "all":"all",
        "tipo":"s/definir",
        "padre":"",
        "version":"old-era",
        "titulo":"holograma",
        "enlace":"http://www.hologramadds.com/",
        "subdominios":[],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online":"offline",
        "imagenSrc":"http://worldshopmart.com/todosProductos/img/default.png"
    },
    {
        "id":37,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"intesplus",
        "enlace":"http://www.intesplus.com/",
        "subdominios":["http://www.intesplus.com/f/","http://www.intesplus.com/index3/","http://www.intesplus.com/mail3/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/intesplus.jpg"
    },
    {
        "id":38,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de xgrande",
        "version":"old-era",
        "titulo":"largemax",
        "enlace":"http://l-maxpro.net/",
        "subdominios":["http://l-maxpro.net/banners/","http://l-maxpro.net/mkt-p/","http://l-maxpro.net/rich-p/","http://l-maxpro.net/zeti-p/","http://l-maxpro.net/sponv-p/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/largemax.jpg"
    },
    {
        "id":39,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de xgrande",
        "version":"old-era",
        "titulo":"largemax",
        "enlace":"http://large-max.com/",
        "subdominios":["http://large-max.com/index2/","http://large-max.com/index3/","http://large-max.com/landingfb/","http://large-max.com/mail2/","http://large-max.com/mail3/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/largemax.jpg"
    },
    {
        "id":40,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de xgrande",
        "version":"old-era",
        "titulo":"largemax",
        "enlace":"http://largemax.com/",
        "subdominios":["http://largemax.com/banner-grande/","http://largemax.com/banner2/","http://largemax.com/banner1631/","http://largemax.com/banner1999/","http://largemax.com/index2/","http://largemax.com/l-max/","http://largemax.com/landing_1/","http://largemax.com/landingfb/","http://largemax.com/mobile/kickads/15/","http://largemax.com/mobile/pml/","http://largemax.com/poringa/3362/","http://largemax.com/mole/3412/","http://largemax.com/mail2/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra": "new-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/largemax.jpg"
    },
    {
        "id":41,
        "all":"all",
        "tipo":"s/definir",
        "padre":"",
        "version":"old-era",
        "titulo":"latamhologram",
        "enlace":"http://www.latamhologram.com/",
        "subdominios":[],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online":"offline",
        "imagenSrc":"http://worldshopmart.com/todosProductos/img/default.png"
    },
    {
        "id":42,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"new-era",
        "titulo":"lipodrene",
        "enlace":"http://www.lipo-drene.com/",
        "subdominios":["http://www.lipo-drene.com/concurso/","http://www.lipo-drene.com/fanpage/","http://www.lipo-drene.com/landing_1/"],
        "responsive": "responsiveSi",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/lipodrene.jpg"
    },
    {
        "id":43,
        "all":"all",
        "tipo":"s/definir",
        "padre":"",
        "version":"old-era",
        "titulo":"lipo",
        "enlace":"http://www.lipofatextreme.com/",
        "subdominios":[],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online":"offline",
        "imagenSrc":"http://worldshopmart.com/todosProductos/img/default.png"
    },
    {
        "id":44,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"secret bra",
        "enlace":"http://www.mascomoda.com/",
        "subdominios":["http://www.mascomoda.com/f/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/secretbra.jpg"
    },
    {
        "id":45,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"mas delgadas",
        "enlace":"http://www.masdelgadas.com/",
        "subdominios":[],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://www.masdelgadas.com/masdelgadas.jpg"
    },
    {
        "id":46,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"mate light",
        "enlace":"http://matelight.net/",
        "subdominios":["http://matelight.net/f/","http://matelight.net/oferta/","http://matelight.net/oferta-tel/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/mateligth.jpg"
    },
    {
        "id":47,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"maxgria",
        "enlace":"http://maxgria.com/",
        "subdominios":["http://maxgria.com/landingfb/","http://maxgria.com/mkt-t/","http://maxgria.com/mobile/kickads/1/","http://maxgria.com/sponv-p/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/maxgria.jpg"
    },
    {
        "id":48,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"new-era",
        "titulo":"blog de productos",
        "enlace":"http://www.mejores-productos.com/",
        "subdominios":[],
        "responsive": "responsiveSi",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://www.mejores-productos.com/wp-content/uploads/2015/12/blog4.jpg"
    },
    {
        "id":49,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"new-era",
        "titulo":"modeline",
        "enlace":"http://www.modelineweb.com/",
        "subdominios":["http://www.modelineweb.com/f/","http://www.modelineweb.com/infobae/3450/","http://www.modelineweb.com/ratingcero/3443/","http://www.modelineweb.com/social/3460/","http://www.modelineweb.com/taringa/3281/"],
        "responsive": "responsiveSi",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra": "new-era",
        "online": "online",
        "imagenSrc":"http://www.modelineweb.com/img/pack1.png"
    },
    {
        "id":50,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"multifeet",
        "enlace":"http://www.multifeet.com/",
        "subdominios":["http://www.multifeet.com/f/","http://www.multifeet.com/contentmktg/","http://www.multifeet.com/diabetic/","http://www.multifeet.com/dp/","http://www.multifeet.com/index1/","http://www.multifeet.com/mail1/","http://www.multifeet.com/mobile/","http://www.multifeet.com/mobile1/","http://www.multifeet.com/sponsorship/","http://www.multifeet.com/zeti/","http://www.multifeet.com/zeti-new/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/multifeet.jpg"
    },
    {
        "id":51,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de lipodrene",
        "version":"old-era",
        "titulo":"naturalweight",
        "enlace":"http://naturalweight.net/",
        "subdominios":["http://naturalweight.net/f/","http://naturalweight.net/index1/","http://naturalweight.net/landing_2/","http://naturalweight.net/mail1/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/naturalweight.jpg"
    },
    {
        "id":52,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de redumas",
        "version":"old-era",
        "titulo":"onceplantas",
        "enlace":"http://www.onceplantas.com/",
        "subdominios":[],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online":"offline",
        "imagenSrc":"http://worldshopmart.com/todosProductos/img/default.png"
    },
    {
        "id":53,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"rewind",
        "enlace":"http://perfect-rewind.com/",
        "subdominios":["http://perfect-rewind.com/f/","http://perfect-rewind.com/index2/","http://perfect-rewind.com/mail2/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/rewind.jpg"
    },
    {
        "id":54,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"plenopausia",
        "enlace":"http://www.plenopausia.com/",
        "subdominios":["http://www.plenopausia.com/dp/","http://www.plenopausia.com/f/","http://www.plenopausia.com/index3/","http://www.plenopausia.com/landing1/","http://www.plenopausia.com/landing2/","http://www.plenopausia.com/mail1/","http://www.plenopausia.com/mail2/","http://www.plenopausia.com/mail3/"],
        "responsive": "responsiveSi",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/plenopausia.jpg"
    },
    {
        "id":55,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de xgrande",
        "version":"new-era",
        "titulo":"powervimax",
        "enlace":"http://www.powervimax.com/",
        "subdominios":["http://www.powervimax.com/banner/","http://www.powervimax.com/banner-grande/","http://www.powervimax.com/poringa/","http://www.powervimax.com/zeti/"],
        "responsive": "responsiveSi",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra": "new-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/powervimax.jpg"
    },
    {
        "id":56,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de calvifin",
        "version":"new-era",
        "titulo":"pro-hair",
        "enlace":"http://pro-hairplus.com/",
        "subdominios":["http://pro-hairplus.com/f/","http://pro-hairplus.com/fbm/","http://pro-hairplus.com/index1/","http://pro-hairplus.com/mail1/","http://pro-hairplus.com/mobile/kickads/banner/","http://pro-hairplus.com/mobile/kickads/insterstitial/"],
        "responsive": "responsiveSi",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/prohair.jpg"
    },
    {
        "id":57,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"productos especiales",
        "enlace":"http://productos-especiales.com/",
        "subdominios":["http://productos-especiales.com/adelmelics/f/","http://productos-especiales.com/corrector/f/","http://productos-especiales.com/dermacel/f/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online":"offline",
        "imagenSrc":"http://worldshopmart.com/todosProductos/img/default.png"
    },
    {
        "id":58,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de prostactive",
        "version":"new-era",
        "titulo":"prosta-pro",
        "enlace":"http://www.prosta-pro.com/",
        "subdominios":["http://www.prosta-pro.com/f/","http://www.prosta-pro.com/index1/","http://www.prosta-pro.com/index3/","http://www.prosta-pro.com/mail1/","http://www.prosta-pro.com/mail3/"],
        "responsive": "responsiveSi",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra": "new-era",
        "online": "online",
        "imagenSrc":"http://www.prosta-pro.com/img/img-05.png"
    },
    {
        "id":59,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"prostactive",
        "enlace":"http://www.prostactive.com/",
        "subdominios":["http://www.prostactive.com/f/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/prostactive.jpg"
    },
    {
        "id":60,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de prostactive",
        "version":"old-era",
        "titulo":"prostaplen",
        "enlace":"http://www.prostaplen.com/",
        "subdominios":["http://www.prostaplen.com/index3/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/prostaplen.jpg"
    },
    {
        "id":61,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"pulmo2",
        "enlace":"http://www.pulmo2.com/",
        "subdominios":["http://www.pulmo2.com/bastadefumar/","http://www.pulmo2.com/darriens/3385/","http://www.pulmo2.com/f/","http://www.pulmo2.com/infobae/3452/","http://www.pulmo2.com/minutouno/3435/","http://www.pulmo2.com/mobile/kickads/3389/","http://www.pulmo2.com/mole/3421/","http://www.pulmo2.com/primicias/3464/","http://www.pulmo2.com/taringa/3280/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra": "new-era",
        "online": "online",
        "imagenSrc":"http://www.pulmo2.com/images/pack.png"
    },
    {
        "id":62,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"redumas",
        "enlace":"http://www.redumas.com/",
        "subdominios":["http://www.redumas.com/fan/","http://www.redumas.com/fan-hombre/","http://www.redumas.com/fbh/","http://www.redumas.com/landingfb/","http://www.redumas.com/mobile/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/redumas.jpg"
    },
    {
        "id":63,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de redumas",
        "version":"new-era",
        "titulo":"redunat",
        "enlace":"http://www.redunat.com/",
        "subdominios":["http://www.redunat.com/f/","http://www.redunat.com/fbh/","http://www.redunat.com/landing_2/"],
        "responsive": "responsiveSi",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra": "new-era",
        "online": "online",
        "imagenSrc":"http://www.redunat.com/img/pack2.png"
    },
    {
        "id":64,
        "all":"all",
        "tipo":"s/definir",
        "padre":"",
        "version":"old-era",
        "titulo":"regenderm",
        "enlace":"http://www.regenderm.com/",
        "subdominios":[],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online":"offline",
        "imagenSrc":"http://worldshopmart.com/todosProductos/img/default.png"
    },
    {
        "id":65,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de calvifin",
        "version":"new-era",
        "titulo":"regrowmaxpro",
        "enlace":"http://www.regrowmaxpro.com/",
        "subdominios":["http://www.regrowmaxpro.com/f/"],
        "responsive": "responsiveSi",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra": "new-era",
        "online": "online",
        "imagenSrc":"http://www.regrowmaxpro.com/img/pack.png"
    },
    {
        "id":66,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de calvifin",
        "version":"new-era",
        "titulo":"rehair",
        "enlace":"http://rehair-max.com/",
        "subdominios":["http://rehair-max.com/dp/","http://rehair-max.com/f/","http://rehair-max.com/index1/","http://rehair-max.com/index3/","http://rehair-max.com/mail1/","http://rehair-max.com/mail3/"],
        "responsive": "responsiveSi",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/rehair.jpg"
    },
    {
        "id":67,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"rejoyfem",
        "enlace":"http://www.rejoyfem.com/",
        "subdominios":["http://www.rejoyfem.com/f/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/rejoy.jpg"
    },
    {
        "id":68,
        "all":"all",
        "tipo":"s/definir",
        "padre":"",
        "version":"old-era",
        "titulo":"resver-plus",
        "enlace":"http://www.resver-plus.com/",
        "subdominios":[],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online":"offline",
        "imagenSrc":"http://worldshopmart.com/todosProductos/img/default.png"
    },
    {
        "id":69,
        "all":"all",
        "tipo":"s/definir",
        "padre":"",
        "version":"old-era",
        "titulo":"revitaltril",
        "enlace":"http://www.revitaltril.com/",
        "subdominios":[],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online":"offline",
        "imagenSrc":"http://worldshopmart.com/todosProductos/img/default.png"
    },
    {
        "id":70,
        "all":"all",
        "tipo":"original",
        "version":"old-era",
        "padre":"",
        "titulo":"sani-sec",
        "enlace":"http://www.sani-sec.com/",
        "subdominios":["http://www.sani-sec.com/contentmktg/","http://www.sani-sec.com/f/","http://www.sani-sec.com/index1/","http://www.sani-sec.com/mail1/","http://www.sani-sec.com/sponsorship/","http://www.sani-sec.com/zeti/","http://www.sani-sec.com/zeti-new/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/sanisec.jpg"
    },
    {
        "id":71,
        "all":"all",
        "tipo":"s/definir",
        "padre":"",
        "version":"old-era",
        "titulo":"sexoybienestar",
        "enlace":"http://www.sexoybienestar.com/",
        "subdominios":["http://www.sexoybienestar.com/vigorsex/","http://www.sexoybienestar.com/virilmax/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online":"offline",
        "imagenSrc":"http://worldshopmart.com/todosProductos/img/default.png"
    },
    {
        "id":72,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de pulmo2",
        "version":"old-era",
        "titulo":"smoke quit",
        "enlace":"http://www.smoke-quit.com/",
        "subdominios":["http://"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online":"offline",
        "imagenSrc":"http://worldshopmart.com/todosProductos/img/default.png"
    },
    {
        "id":73,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de sanisec",
        "version":"old-era",
        "titulo":"sudorblock",
        "enlace":"http://www.sudorblock.com/",
        "subdominios":[],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online":"offline",
        "imagenSrc":"http://worldshopmart.com/todosProductos/img/default.png"
    },
    {
        "id":74,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de durasex",
        "version":"old-era",
        "titulo":"tempovit",
        "enlace":"http://www.tempovit.com/",
        "subdominios":["http://www.tempovit.com/contentmktg/","http://www.tempovit.com/f/","http://www.tempovit.com/index1/","http://www.tempovit.com/index3/","http://www.tempovit.com/mail1/","http://www.tempovit.com/mail3/","http://www.tempovit.com/sponsorship/","http://www.tempovit.com/zeti/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/tempovit.jpg"
    },
    {
        "id":75,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"ultralash",
        "enlace":"http://ultralash.net/",
        "subdominios":[],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://ultralash.net/img/beneficios.jpg"
    },
    {
        "id":76,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"varilyne",
        "enlace":"http://www.varilyne.com/",
        "subdominios":["http://www.varilyne.com/f/","http://www.varilyne.com/index2/","http://www.varilyne.com/mail2/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/varilyne.jpg"
    },
    {
        "id":77,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de crembios",
        "version":"old-era",
        "titulo":"celulift",
        "enlace":"http://vertebien.net/",
        "subdominios":["http://vertebien.net/concurso/","http://vertebien.net/f/","http://vertebien.net/index1/","http://vertebien.net/mail1/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/celulift.jpg"
    },
    {
        "id":78,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de maxgria",
        "version":"old-era",
        "titulo":"vigomax",
        "enlace":"http://www.vigo-power.com/",
        "subdominios":["http://www.vigo-power.com/andes/","http://www.vigo-power.com/andes_voz/","http://www.vigo-power.com/index1/","http://www.vigo-power.com/layer/","http://www.vigo-power.com/mail1/","http://www.vigo-power.com/mkt-p/","http://www.vigo-power.com/sponv-p/","http://www.vigo-power.com/zeti-p/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/vigomax.jpg"
    },
    {
        "id":79,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de maxgria",
        "version":"old-era",
        "titulo":"vigramax",
        "enlace":"http://www.vigramax.com/",
        "subdominios":["http://www.vigramax.com/landing_1/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/vigramax.jpg"
    },
    {
        "id":80,
        "all":"all",
        "tipo":"s/definir",
        "padre":"",
        "version":"old-era",
        "titulo":"virtualityadds",
        "enlace":"http://www.virtualityadds.com/",
        "subdominios":[],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online":"offline",
        "imagenSrc":"http://worldshopmart.com/todosProductos/img/default.png"
    },
    {
        "id":81,
        "all":"all",
        "tipo":"s/definir",
        "padre":"",
        "version":"old-era",
        "titulo":"virtuallatam",
        "enlace":"http://www.virtuallatam.com/",
        "subdominios":[],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online":"offline",
        "imagenSrc":"http://worldshopmart.com/todosProductos/img/default.png"
    },
    {
        "id":82,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de alivialiv",
        "version":"old-era",
        "titulo":"vitalflex",
        "enlace":"http://vitalflex.net/",
        "subdominios":["http://vitalflex.net/f/","http://vitalflex.net/index1/","http://vitalflex.net/mail1/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/vitalflex.jpg"
    },
    {
        "id":83,
        "all":"all",
        "tipo":"s/definir",
        "padre":"",
        "version":"old-era",
        "titulo":"vrlatinoamerica",
        "enlace":"http://www.vrlatinoamerica.com/",
        "subdominios":[],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online":"offline",
        "imagenSrc":"http://worldshopmart.com/todosProductos/img/default.png"
    },
    {
        "id":84,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"worldshopmart",
        "enlace":"http://worldshopmart.com/",
        "subdominios":[],
        "responsive": "responsiveSi",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/_layout/images/logo.png"
    },
    {
        "id":85,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de redumas",
        "version":"old-era",
        "titulo":"xenicla",
        "enlace":"http://xenicla.net/",
        "subdominios":["http://xenicla.net/f/","http://xenicla.net/index1/","http://xenicla.net/index2/","http://xenicla.net/index3/","http://xenicla.net/landing_1/","http://xenicla.net/landing_2/","http://xenicla.net/mail1/","http://xenicla.net/mail2/","http://xenicla.net/mail3/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra": "new-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/xenicla.jpg"
    },
    {
        "id":86,
        "all":"all",
        "tipo":"original",
        "padre":"",
        "version":"old-era",
        "titulo":"xgrande",
        "enlace":"http://xgrande.com/",
        "subdominios":["http://xgrande.com/darriens/3382/","http://xgrande.com/f/","http://xgrande.com/kickads/3320/","http://xgrande.com/mole/3415/","http://xgrande.com/poringa/3368/","http://xgrande.com/primicias/3475/","http://xgrande.com/ratingcero/3440/","http://xgrande.com/teleshow/3455/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "subResponsive",
        "subdominioNewEra": "new-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/xgrande.jpg"
    },
    {
        "id":87,
        "all":"all",
        "tipo":"clon",
        "padre":"clon de xgrande",
        "version":"old-era",
        "titulo":"xlarge",
        "enlace":"http://www.xlargegel.com/",
        "subdominios":["http://www.xlargegel.com/fb/","http://www.xlargegel.com/fb2/","http://www.xlargegel.com/landing_1/","http://www.xlargegel.com/landing_2/"],
        "responsive": "noResponsive",
        "subdominioResponsive": "noResponsive",
        "subdominioNewEra":"old-era",
        "online": "online",
        "imagenSrc":"http://worldshopmart.com/img/xlarge.jpg"
    }
];
